"""credentials update and create dates

Revision ID: 03b5f1ac990a
Revises: 12b961001688
Create Date: 2025-02-18 12:24:38.686993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b5f1ac990a'
down_revision: Union[str, None] = '12b961001688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passports', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('passports', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('visa_center_credentials', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('visa_center_credentials', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visa_center_credentials', 'updated_at')
    op.drop_column('visa_center_credentials', 'created_at')
    op.drop_column('passports', 'updated_at')
    op.drop_column('passports', 'created_at')
    # ### end Alembic commands ###
