"""creation and update dates added to card

Revision ID: 12b961001688
Revises: bdb93840a237
Create Date: 2025-02-18 12:01:57.385269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b961001688'
down_revision: Union[str, None] = 'bdb93840a237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('cards', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'updated_at')
    op.drop_column('cards', 'created_at')
    # ### end Alembic commands ###
