"""Relationship to relationship

Revision ID: 6287844bb8c8
Revises: 03b5f1ac990a
Create Date: 2025-02-18 12:55:15.827019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6287844bb8c8'
down_revision: Union[str, None] = '03b5f1ac990a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
