"""visa center model

Revision ID: 6718c80d2e70
Revises: 722efe47edca
Create Date: 2025-02-25 18:08:33.351071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6718c80d2e70'
down_revision: Union[str, None] = '722efe47edca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visa_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visa_centers_id'), 'visa_centers', ['id'], unique=False)
    op.create_index(op.f('ix_visa_centers_name'), 'visa_centers', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visa_centers_name'), table_name='visa_centers')
    op.drop_index(op.f('ix_visa_centers_id'), table_name='visa_centers')
    op.drop_table('visa_centers')
    # ### end Alembic commands ###
