"""passport list in user model

Revision ID: 7d9f0780375d
Revises: 638afea3d136
Create Date: 2025-01-26 12:53:14.724476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9f0780375d'
down_revision: Union[str, None] = '638afea3d136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_phone_otps_id', table_name='phone_otps')
    op.drop_index('ix_phone_otps_otp', table_name='phone_otps')
    op.drop_index('ix_phone_otps_phone_number', table_name='phone_otps')
    op.drop_table('phone_otps')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_phone_number', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_tokens_id', table_name='tokens')
    op.drop_index('ix_tokens_token', table_name='tokens')
    op.drop_index('ix_tokens_user_id', table_name='tokens')
    op.drop_table('tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tokens_user_id', 'tokens', ['user_id'], unique=False)
    op.create_index('ix_tokens_token', 'tokens', ['token'], unique=False)
    op.create_index('ix_tokens_id', 'tokens', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_phone_number', 'users', ['phone_number'], unique=1)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('phone_otps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), nullable=True),
    sa.Column('otp', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_phone_otps_phone_number', 'phone_otps', ['phone_number'], unique=1)
    op.create_index('ix_phone_otps_otp', 'phone_otps', ['otp'], unique=False)
    op.create_index('ix_phone_otps_id', 'phone_otps', ['id'], unique=False)
    # ### end Alembic commands ###
