"""nullable=False in passport params

Revision ID: ac3a039b2a3b
Revises: 2ba0efdea020
Create Date: 2025-01-26 13:03:40.340155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac3a039b2a3b'
down_revision: Union[str, None] = '2ba0efdea020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
