"""add_onupdate_to_phone_otp_created_at

Revision ID: da9498858761
Revises: 45382d7e0da3
Create Date: 2025-03-23 22:02:42.662923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da9498858761'
down_revision: Union[str, None] = '45382d7e0da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phone_otps', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               existing_nullable=True,
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phone_otps', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               existing_nullable=True,
               server_default=None,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
